### ISSUE TITLE
sizeFull breaks flex containers

### ISSUE THREAD

**Issue by VinSpee** [suitcss/utils-size#32]
Hi! I'm using this with the `Grid` component and running into an issue. When I use the `Grid--withGutter` modifier, I have to add `u-sizeFull` to the container or else it overflows, which is normally fine, but since switching to the flexbox-based grid, `u-sizeFull` [forcibly sets display to block](https://github.com/suitcss/utils-size/blob/master/lib/size.css#L168).

Am I doing something wrong or is there a workaround?

**Comment by simonsmith** [comment]
What is the issue you're trying to resolve by having `sizeFull` on the `Grid` container?

**Comment by VinSpee** [comment]
given the following code:

```html
<div class="Grid Grid--withGutter">
  <div class="Grid-cell u-lg-size3of12">
    hello
  </div>
  <div class="Grid-cell u-lg-size9of12">
    world
  </div>
</div>
```

I am left with a Grid that is causing the page to scroll horizontally. adding `style="width: 100%;"` to the `Grid` corrects this problem. Is that clear?

**Comment by simonsmith** [comment]
Hmm, are you sure nothing else is effecting the grid? I modified the Grid tests in devtools to simulate and it seems fine:

<img width="972" alt="screen shot 2015-12-08 at 14 54 06" src="https://cloud.githubusercontent.com/assets/360703/11658656/a630ff70-9dbb-11e5-9bd0-ca8205edf385.png">

``` html
<div class="Grid Grid--withGutter">
  <div class="Grid-cell u-size3of12">content</div>
  <div class="Grid-cell u-size9of12">content</div>
</div>
```

**Comment by VinSpee** [comment]
If you remove the `padding` on the `.Test` fixture, you will see the overflow:

![screen shot 2015-12-08 at 10 04 06 am](https://cloud.githubusercontent.com/assets/582828/11658873/2a056166-9d93-11e5-85a3-7418107a8a72.png)

**Comment by simonsmith** [comment]
Looking okay here, with minimal styles - http://codepen.io/simonsmith/full/LGEBqO/

What browser are you using?

**Comment by VinSpee** [comment]
same issue - firefox aurora.

<img width="961" alt="screen shot 2015-12-08 at 2 27 38 pm" src="https://cloud.githubusercontent.com/assets/582828/11665949/ee2d5f3e-9db7-11e5-8545-995bfdbafee8.png">

**Comment by giuseppeg** [comment]
<blockquote>Looking okay here, with minimal styles - http://codepen.io/simonsmith/full/LGEBqO/
What browser are you using?</blockquote>

I am able to reproduce the issue. The `fixture-Box` is overflowing (see the right edge of of `Grid-cell`)

<img width="230" alt="screen shot 2015-12-08 at 12 21 45 pm" src="https://cloud.githubusercontent.com/assets/711311/11667390/4fa72202-9da6-11e5-8c00-d32c62b105e2.png">

**Comment by simonsmith** [comment]
Okay, so the tests may need a tweak as those elements don't need `width: 100%` on them. Presuming you don't set that on your content I'm still not sure what the issue is. Tweaked example from before, but with background color http://codepen.io/simonsmith/pen/LGEBqO

I'm also using the Grid on [my site](http://simonsmith.io/) with no visible overflow. I might be missing something though, so do you have a test example that reproduces your issue @VinSpee?

**Comment by VinSpee** [comment]
Busy week - I will get you a minimal codepen example first thing tomorrow.

**Comment by VinSpee** [comment]
@simonsmith [Here's a fork of your pen](http://codepen.io/VinSpee/pen/WrQBzR?editors=110). It seems that having `margin: 0` on body is what's causing the issue. Any ideas?

**Comment by VinSpee** [comment]
maybe it's related to `Grid--withGutters`?

**Comment by simonsmith** [comment]
I think this is expected behaviour.

Using `Grid--withGutter` on a full width element is always going to exceed it's bounds based on the fact it using negative margins. Typically you'd always have a `Container` element of some description that had appropriate margin or padding each side. Most grid systems require this (bootstrap springs to mind).

It's worth noting that the same issue happens on the 2.x version of the Grid as well, so this doesn't seem related to Flex.

What's your use case that is causing this issue?
