### ISSUE TITLE
Sizes using calc with trailing decimals cause Grid-cell's to wrap in Internet Explorer 10 & 11

### ISSUE THREAD

**Issue by dcalhoun** [suitcss/utils-size#33]
From my experience, IE 10 and 11 fail to consistently calculate the appropriate width of a `Grid-cell` when paired with a `u-sizeXofY` that contains a repeating decimal value (e.g. – 33.3333333%, 16.666667%) within the `width` attribute. When it fails to calculate the correct width, `Grid-cell`'s are erroneously bumped/wrapped to the next line.

I've created [a CodePen to demonstrate the issue](http://codepen.io/davidcalhoun/pen/dGLyem/). If you visit the link in IE 10 or 11 and slowly resize the window, the cells will jump around at arbitrary window widths.

Is this a known issue? Is there way to resolve this?

**Comment by simonsmith** [comment]
I couldn't run your CodePen in IE10 because the Grid needs to be preprocessed and autoprefixed. However the Grid visual tests seem to work fine in IE10. Here's a demo of me resizing IE10 - http://cl.ly/fAjq

Do you see the same issue in the visual tests too? http://suitcss.github.io/components-grid/test/

**Comment by dcalhoun** [comment]
Sorry, I didn't think about Grid needing autoprefixer. The preprocessor shouldn't matter given that the only item needed is the `--Grid-gutter-size`, which I'm not using in the CodePen example. I would think IE would skip over that erroneous, unsupported syntax. Regardless, I have [updated the CodePen example](http://codepen.io/davidcalhoun/pen/dGLyem/) to include an inlined, autoprefixed version of the v3.0.2 Grid file without CSS custom properties.

No, the problem does *not* appear in your demo or in the visual tests, but I think that's for two reasons:

1. You are demoing a "1 of 4" section, which does *not* use `calc()` and would *not* have a repeating decimal (i.e. – it's a flat 25%).
2. Correct me if I'm wrong, but, after inspecting the visual tests, they appear to *not* be using `calc()` and repeating decimals. [It appears to be using a version of the size utility with inlined, non-`calc()` percentages](https://github.com/suitcss/components-grid/blob/gh-pages/build/test.css#L130-L134).

For example, the CSS from the visual tests for `.u-size1of3` uses `width: 33.33333% !important;`. The CSS [found in the latest size utility](https://github.com/suitcss/utils-size/blob/1.0.2/lib/size.css#L56-L60) is `width: calc(100% * 1 / 3) !important;`.

Is this an oversight in the visual tests or is my build process supposed to replace the use of `calc()` with inlined, non-`calc()` percentages (e.g. – `33.33333%` replaces `calc(100% * 1 / 3)`)?

**Comment by simonsmith** [comment]
>  is my build process supposed to replace the use of calc() with inlined, non-calc() percentages (e.g. – 33.33333% replaces calc(100% * 1 / 3))

Yeah, this looks like the issue. I can reproduce it in IE as well if I use `calc(100% * 1 / 3)` instead of `33.33333%`.

Taken from the [caniuse page](http://caniuse.com/#search=calc):

> Due to the way browsers handle sub-pixel rounding differently, layouts using calc() expressions may have unexpected results.

I would suggest usage of [postcss-calc](https://github.com/postcss/postcss-calc) which is included in the [suitcss-preprocessor](https://github.com/suitcss/preprocessor) by default. 

I've updated your CodePen example with a preprocessed version of `utils-size` - http://codepen.io/simonsmith/pen/MKROOw This should work fine in IE

**Comment by dcalhoun** [comment]
Alright. Thanks for the help. I'm not using PostCSS for my build currently, but I'll manually reduce those `calc()`'s to resolve the issue.

**Comment by simonsmith** [comment]
No worries. You should be able to clone this repo and run `npm i && npm run build` to generate a `build.css` if you don't wish to do it manually.
